In [3]:
import pandas as pd
import numpy as np

In [3]:
a = [1,2,3,4,5,6]

In [6]:
s = pd.Series(a)
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [7]:
d = {"aman":100, "rohan":89, "shivam":67}
s = pd.Series(d)
s

aman      100
rohan      89
shivam     67
dtype: int64

In [10]:
df = pd.DataFrame({
    "name":["Aman", "Rohit"],
    "salary":[2000, 4000]
})
df

    name  salary
0   Aman    2000
1  Rohit    4000

In [ ]:
df = pd.read_csv('./employees_100.csv')
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [13]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [14]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [15]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
93,183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09

In [16]:
df.shape

(100, 10)

In [18]:
df.dtypes

employee_id             int64
name                      str
department                str
city                      str
age                   float64
salary                    str
experience              int64
performance_score       int64
projects_completed      int64
joining_date              str
dtype: object

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 7.9 KB

In [20]:
df.describe()

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [21]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [7]:
df[['name','salary']]

              name salary
0     Swati Kapoor  70719
1   Kavya Malhotra  77058
2     Manish Desai  69911
3         Neha Das  69993
4        Isha Nair  88216
..             ...    ...
95     Nikhil Nair  55740
96      Neha Desai  52250
97      Neha Reddy    NaN
98     Priya Nayak  56821
99     Kavya Joshi  69499

[100 rows x 2 columns]

In [8]:
df = df.set_index("employee_id")
df

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25